Fix finding of pkgsrc/mk/check-portability.awk:
ERROR: [check-portability.awk] => Found test ... == ...:
ERROR: [check-portability.awk] configure: if test "x$ac_cv_unspecified_size_last_struct_member" == "xyes"; then :
ERROR: [check-portability.awk] configure: if test "x$ac_cv_zero_array_size" == "xyes"; then :

Explanation:
===========================================================================
The "test" command, as well as the "[" command, are not required to know
the "==" operator. Only a few implementations like bash and some
versions of ksh support it.